### PR TITLE
handle no error retun

### LINKED ISSUE #15: Consider panicing (or similar) for functions without return values
Split out of #1 

From @fatih:

```
func foo() {
	// I want to panic here
	bar()

}

func bar() error {
	return errors.New("foo")
}
```

When I call `:GoExpandErr` when my cursor is on `bar()~ inside `foo()` I got this error:

```
2017/12/28 18:04:49 current function returns no values, cannot return error
```

I think if there are no returns, it should default to `panic(err.Error())` or something alike.

### PR DESCRIPTION
**Pull request by wsny**
Fixes #15

Goes a little further than suggested to also cover cases where there are return values, but no errors. Seems rare, but gives people more rope to do what they want with. First time digging this deep into this stuff so happy to hear any/all suggestions.

### CODE REVIEW

File: expanderr.go [hunk 1]
```diff
@@ -387,13 +392,30 @@ func (e *expansion) typeCheck(pkgname string, files []*ast.File) error {
...
-	if e.ce == nil {
-		return fmt.Errorf("no ast.CallExpr found")
+type noErrTemplateFields struct {
+	Err    string // generally just "err", but not something the caller controlls
+	Return string // the entire return string
+}
+
+func noErrorReturn(fields noErrTemplateFields) (string, error) {
+	if *noErrTemplate == "" {
+		return "panic(err.Error())", nil
```
Comment (stapelberg) [inline expanderr.go]: Instead of `panic(err.Error())`, just use `panic(err)`

File: expanderr.go [hunk 2]
```diff
@@ -387,13 +392,30 @@ func (e *expansion) typeCheck(pkgname string, files []*ast.File) error {
...
 		}
 	}
+	return nil
+}
 
-	e.ce = callExprAtPath(e.path)
-	if e.ce == nil {
-		return fmt.Errorf("no ast.CallExpr found")
+type noErrTemplateFields struct {
+	Err    string // generally just "err", but not something the caller controlls
```
Comment (stapelberg) [inline expanderr.go]: typo: controlls → controls

File: expanderr.go [hunk 3]
```diff
@@ -387,13 +392,30 @@ func (e *expansion) typeCheck(pkgname string, files []*ast.File) error {
...
+}
+
+func noErrorReturn(fields noErrTemplateFields) (string, error) {
+	if *noErrTemplate == "" {
+		return "panic(err.Error())", nil
 	}
-	e.callee, err = signatureOf(e.info, e.ce)
-	return err
+
+	templ, err := template.New("noErr").Parse(*noErrTemplate)
```
Comment (stapelberg) [inline expanderr.go]: Can you move parsing the template to main() please? That way, we can fail early.

File: expanderr.go [hunk 4]
```diff
@@ -534,6 +578,30 @@ func logic(w io.Writer, buildctx *build.Context, posn string) error {
 			as.Lhs = append(as.Lhs, &ast.Ident{Name: "err"})
 		}
 
+		var outputStmt ast.Stmt = &ast.ReturnStmt{Results: e.results}
```
Comment (stapelberg) [inline expanderr.go]: This logic looks like a duplicate with the logic above? Can it be refactored into a helper function?

File: expanderr.go [hunk 5]
```diff
@@ -672,12 +738,12 @@ func logic(w io.Writer, buildctx *build.Context, posn string) error {
 }
 
 var (
-	wFlag      = flag.String("w", "", "write")
-	formatFlag = flag.String("format", "", "output format (source, json). defaults to 'source'")
+	wFlag         = flag.String("w", "", "write")
+	formatFlag    = flag.String("format", "", "output format (source, json). defaults to 'source'")
+	cpuprofile    = flag.String("cpuprofile", "", "write cpu profile `file`")
+	noErrTemplate = flag.String("no-error-template", "", "template to be used if there is no error return value. defaults to a panic")
```
Comment (stapelberg) [inline expanderr.go]: In the documentation, let’s add an example, and mention that the syntax is Go’s text/template package.

File: lisp/go-expanderr.el [hunk 6]
```diff
@@ -25,12 +25,12 @@
           (with-current-buffer patchbuf
             (erase-buffer))
 
-	  (save-buffer)
```
Comment (stapelberg) [inline lisp/go-expanderr.el]: You’re not making any changes to this file, yet your editor seems to have reformatted it. Could you revert this please? We’d like to keep the git history as clean as possible :)

**Review by stapelberg — CHANGES_REQUESTED** [review]
Thanks for the PR!

**Comment by wsny** [comment]
I've got some fixes for some of the other issues, would you like a PR for each or one PR with everything? (9, 13 and 14)

**Comment by stapelberg** [comment]
One logical change per PR please :)

File: expanderr.go [hunk 7]
```diff
@@ -709,7 +756,18 @@ func main() {
 		o = f
 	}
 
-	if err := logic(o, &build.Default, posn); err != nil {
+	var (
+		templ *template.Template
+		err   error
```
Comment (stapelberg) [inline expanderr.go]: Please scope err as narrowly as possible, i.e. move “var err error” into the if *noErrTemplate conditional

File: expanderr.go [hunk 8]
```diff
@@ -387,16 +392,52 @@ func (e *expansion) typeCheck(pkgname string, files []*ast.File) error {
...
+	return nil
+}
 
-	e.ce = callExprAtPath(e.path)
-	if e.ce == nil {
-		return fmt.Errorf("no ast.CallExpr found")
+// this function either returns just the return values of the function or, if there are no errors
+// returned, will also add in the no-error-return-template
+func (e *expansion) getFinalOutput(noReturnTempl *template.Template, errName string) (ast.Stmt, error) {
+	var normalReturn ast.Stmt = &ast.ReturnStmt{Results: e.results}
```
Comment (stapelberg) [inline expanderr.go]: Can you just use `normalReturn := &ast.ReturnStmt{Results: e.results}` here?

File: expanderr.go [hunk 9]
```diff
@@ -387,16 +392,52 @@ func (e *expansion) typeCheck(pkgname string, files []*ast.File) error {
...
 	}
-	e.callee, err = signatureOf(e.info, e.ce)
-	return err
+
+	if returnsError {
+		return normalReturn, nil
+	}
+
+	if noReturnTempl == nil { // default output when no error retuned
+		return &ast.ExprStmt{X: &ast.Ident{Name: "panic(err)"}}, nil
```
Comment (stapelberg) [inline expanderr.go]: I only noticed this now: here and when evaluating the template, you are essentially stuffing Go code into an ast.Ident.

While this might work fine today, it seems brittle and incorrect. For the literal here, it’s easy to change. Can you please look into parsing the template output into ast nodes, too?

**Review by stapelberg — CHANGES_REQUESTED** [review]

File: expanderr.go (hunk 7 above)
Comment (wsny) [reply expanderr.go]: I feel like I'm missing something simple here.
```go
	var templ *template.Template
	if *noErrTemplate != "" {
->	templ, err = template.New("noErr").Parse(*noErrTemplate)
		if err != nil {
			log.Fatalf("error parsing no-error-template: %v", err)
		}
	}

	if err := logic(o, &build.Default, posn, templ); err != nil {
		log.Fatal(err)
	}
```
This gets me a `templ declared and not used`, so I used the above hack to make it happy. I'm blanking on what the 'right' thing to do here is.

Comment (stapelberg) [reply expanderr.go]: You’re probably using := instead of =.

My point was that the declaration of err should be within the conditional block:

```go
var templ *template.Template
	if *noErrTemplate != "" {
var err error
	templ, err = template.New("noErr").Parse(*noErrTemplate)
		if err != nil {
			log.Fatalf("error parsing no-error-template: %v", err)
		}
	}
```

File: expanderr.go (hunk 9 above)
Comment (wsny) [reply expanderr.go]: I looked into parsing the template into ast. The `go/parser` package doesn't seem to support any multiline statements that are not part of an entire file. Basically if its fine to assume that anyone would ever only want a single to do what they want with the error, and that if you're not using the default panic you'd like a return statement as well, we can get rid of the template all together and just let the user pass in a single statement that we can parse and always put in the return after.

File: expanderr.go [hunk 10]
```diff
@@ -617,8 +658,9 @@ func logic(w io.Writer, buildctx *build.Context, posn string) error {
 		// Hack: inline comments (e.g. os.Remove("/foo" /* path */)) get lost
 		// when formatting node, so we string-replace the formatted CallExpr
 		// with the original CallExpr.
+
 		var stmtFmt, ceFmt bytes.Buffer
-		if err := format.Node(&stmtFmt, e.fset, node); err != nil {
+		if err := format.Node(&stmtFmt, token.NewFileSet(), node); err != nil {
```
Comment (wsny) [inline expanderr.go:663]: Not sure why, but only with longer `no-err-callback`'s, This statement will format the node very strangely over multiple lines when using the same `e.fset` that is used everywhere else, and for some reason using a new one here fixes it. Have not seen any side affects from doing it this way, but it is not clear to me what its used for in this statement.

**Comment by wsny** [comment]
Simplified things by removing the template, which made it possible to parse things int AST in all cases. I'd guess that something simple like this would be the most common anyway, and for the more rare occasions you can always just go back and fix it after the tool is done.

File: expanderr.go (hunk 10 above)
Comment (stapelberg) [reply expanderr.go:663]: Not entirely obvious to me either.

Ideally, we should change the code to use https://github.com/dave/dst to resolve the comment above regarding inline comments, and perhaps that would also address whichever weirdness we’re running into here :)

**Review by stapelberg — APPROVED** [review]

**Comment by stapelberg** [comment]
Thanks!
